# Generated by Django 6.0.6 on 2026-06-20 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_provide_688176_idx',
            old_name='reviews_rev_provide_75377a_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_custome_12a99d_idx',
            old_name='reviews_rev_custome_6d90f0_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_rating_2db6dd_idx',
            old_name='reviews_rev_rating_9c5446_idx',
        ),
    ]
