import { Link } from "react-router-dom";
import { BadgeCheck, Clock3, MapPin, Star } from "lucide-react";
import type { Provider, Service } from "@/types/api";
import { money } from "@/lib/utils";
import { Badge } from "./ui/badge";
import { Card } from "./ui/card";

export function ServiceCard({ service }: { service: Service }) { return <Link to={`/services/${service.id}`} className="group block"><Card className="h-full overflow-hidden"><div className="aspect-[16/10] overflow-hidden bg-secondary"><img src={service.image_url} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /></div><div className="p-4"><div className="flex items-center justify-between gap-2"><Badge>{service.category?.name || "Service"}</Badge><span className="flex items-center gap-1 text-xs font-semibold"><Star className="size-3 fill-warning text-warning" />{service.average_rating.toFixed(1)}</span></div><h3 className="mt-3 line-clamp-1 text-lg font-bold">{service.name}</h3><p className="mt-1 flex items-center gap-1 text-sm text-muted-foreground">{service.provider.is_verified && <BadgeCheck className="size-4 text-primary" />}{service.provider.full_name} · {service.provider.city || "Local"}</p><div className="mt-4 flex items-end justify-between"><span className="font-display text-lg font-bold">{money(service.price)}</span><span className="flex items-center gap-1 text-xs text-muted-foreground"><Clock3 className="size-3.5" />{service.duration_hours} hr</span></div></div></Card></Link>; }
export function ProviderCard({ provider }: { provider: Provider }) { return <Link to={`/providers/${provider.id}`} className="group block"><Card className="h-full p-5"><div className="flex items-start gap-4"><div className="grid size-14 shrink-0 place-items-center overflow-hidden rounded-2xl bg-gradient-brand text-xl font-bold text-white">{provider.profile_picture_url ? <img src={provider.profile_picture_url} alt="" className="h-full w-full object-cover" /> : provider.full_name.charAt(0)}</div><div className="min-w-0"><div className="flex items-center gap-1.5"><h3 className="truncate text-lg font-bold">{provider.full_name}</h3>{provider.is_verified && <BadgeCheck className="size-4 shrink-0 text-primary" />}</div><p className="mt-1 flex items-center gap-1 text-sm text-muted-foreground"><MapPin className="size-3.5" />{provider.city || "Local provider"}</p></div></div><p className="mt-4 line-clamp-2 text-sm leading-6 text-muted-foreground">{provider.description || "Experienced local professional ready to help."}</p><div className="mt-5 grid grid-cols-3 gap-2 rounded-xl bg-secondary/70 p-3 text-center"><Metric value={provider.average_rating.toFixed(1)} label="Rating" /><Metric value={String(provider.jobs_completed)} label="Jobs" /><Metric value={`${provider.experience_years}y`} label="Experience" /></div></Card></Link>; }
function Metric({ value, label }: { value: string; label: string }) { return <div><p className="font-display text-sm font-bold">{value}</p><p className="text-[10px] uppercase tracking-wide text-muted-foreground">{label}</p></div>; }
