import { useState } from "react";
import { Link, NavLink, Outlet } from "react-router-dom";
import { Menu, X } from "lucide-react";
import { Logo } from "./brand";
import { Button } from "./ui/button";
import { useAuth } from "@/hooks/use-auth";

const links = [{ to: "/services", label: "Browse services" }, { to: "/providers", label: "Top pros" }, { to: "/#how-it-works", label: "How it works" }, { to: "/register?role=PROVIDER", label: "For providers" }];
export default function SiteLayout() {
  const [open, setOpen] = useState(false);
  const { authenticated } = useAuth();
  return <div className="min-h-screen"><header className="sticky top-0 z-40 border-b bg-background/85 backdrop-blur-xl"><div className="container-page flex h-16 items-center justify-between"><div className="flex items-center gap-8"><Logo /><nav className="hidden items-center gap-1 md:flex">{links.map((link) => <NavLink key={link.to} to={link.to} className="rounded-lg px-3 py-2 text-sm font-medium text-muted-foreground hover:bg-secondary hover:text-foreground">{link.label}</NavLink>)}</nav></div><div className="flex items-center gap-2">{authenticated ? <Button asChild size="sm"><Link to="/dashboard">Dashboard</Link></Button> : <><Button asChild size="sm" variant="ghost" className="hidden sm:inline-flex"><Link to="/login">Sign in</Link></Button><Button asChild size="sm"><Link to="/register">Get started</Link></Button></>}<button onClick={() => setOpen(!open)} className="grid size-9 place-items-center rounded-lg border md:hidden" aria-label="Toggle menu">{open ? <X className="size-4" /> : <Menu className="size-4" />}</button></div></div>{open && <nav className="container-page flex flex-col gap-1 border-t py-3 md:hidden">{links.map((link) => <Link key={link.to} to={link.to} onClick={() => setOpen(false)} className="rounded-lg px-3 py-2 text-sm font-medium text-muted-foreground hover:bg-secondary">{link.label}</Link>)}</nav>}</header><Outlet /><footer className="border-t bg-background"><div className="container-page grid gap-8 py-12 sm:grid-cols-2 lg:grid-cols-4"><div><Logo /><p className="mt-4 max-w-xs text-sm leading-6 text-muted-foreground">Trusted local professionals, transparent pricing, and a simpler way to get things done.</p></div><FooterGroup title="Explore" items={["Services", "Providers", "How it works"]} /><FooterGroup title="Company" items={["About", "Trust & safety", "Help centre"]} /><div><p className="font-display font-bold">Built for your neighbourhood</p><p className="mt-3 text-sm text-muted-foreground">Secure payments · Verified pros · Real reviews</p></div></div><div className="border-t py-5 text-center text-xs text-muted-foreground">© {new Date().getFullYear()} Servora. Local help, thoughtfully delivered.</div></footer></div>;
}
function FooterGroup({ title, items }: { title: string; items: string[] }) { return <div><p className="font-display font-bold">{title}</p><ul className="mt-3 space-y-2 text-sm text-muted-foreground">{items.map((item) => <li key={item}>{item}</li>)}</ul></div>; }
