import { useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarDays, MessageCircle, Star } from "lucide-react";
import { useState } from "react";
import { Link } from "react-router-dom";
import { api, ensureCsrf, formData } from "@/lib/api";
import { money, shortDate } from "@/lib/utils";
import type { Booking, ListResponse } from "@/types/api";
import { useAuth } from "@/hooks/use-auth";
import { Empty, Loading, PageIntro } from "@/components/states";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/input";
export default function BookingsPage() { const [status, setStatus] = useState(""); const { user } = useAuth(); const client = useQueryClient(); const query = useQuery({ queryKey: ["bookings", status], queryFn: async () => (await api.get<ListResponse<Booking>>(`/bookings/?page_size=50${status ? `&status=${status}` : ""}`)).data }); const setBookingStatus = async (id: number, value: string) => { await ensureCsrf(); await api.post(`/bookings/${id}/status/`, formData({ status: value })); await client.invalidateQueries({ queryKey: ["bookings"] }); }; return <><PageIntro eyebrow="Your schedule" title="Bookings" description="Follow each request from pending to completed. Payment confirmation remains webhook-driven." /><div className="mb-5 flex flex-wrap gap-2">{["", "PENDING", "CONFIRMED", "ACCEPTED", "COMPLETED", "REJECTED"].map((item) => <button key={item} onClick={() => setStatus(item)} className={`rounded-full px-3 py-1.5 text-xs font-bold ${status === item ? "bg-primary text-white" : "bg-background text-muted-foreground"}`}>{item || "ALL"}</button>)}</div>{query.isLoading ? <Loading /> : query.data?.results.length ? <div className="space-y-4">{query.data.results.map((booking) => <div key={booking.id} className="rounded-2xl border bg-background p-5 shadow-card"><div className="flex flex-col gap-4 lg:flex-row lg:items-center"><div className="grid size-12 shrink-0 place-items-center rounded-2xl bg-primary-soft text-primary"><CalendarDays className="size-5" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">{booking.service.name}</h2><Badge>{booking.status_label}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{user?.role === "PROVIDER" ? booking.customer.full_name : booking.provider.full_name} · {shortDate(booking.booking_date)}</p>{booking.notes && <p className="mt-2 line-clamp-1 text-xs text-muted-foreground">“{booking.notes}”</p>}</div><p className="font-display text-lg font-extrabold">{money(booking.service.price)}</p><div className="flex flex-wrap gap-2"><Button asChild size="sm" variant="outline"><Link to={`/messages?partner=${user?.role === "PROVIDER" ? booking.customer.id : booking.provider.id}`}><MessageCircle className="size-4" />Message</Link></Button>{user?.role === "PROVIDER" && booking.status === "PENDING" && <><Button size="sm" onClick={() => setBookingStatus(booking.id, "ACCEPTED")}>Accept</Button><Button size="sm" variant="outline" onClick={() => setBookingStatus(booking.id, "REJECTED")}>Decline</Button></>}{user?.role === "PROVIDER" && ["CONFIRMED", "ACCEPTED"].includes(booking.status) && <Button size="sm" onClick={() => setBookingStatus(booking.id, "COMPLETED")}>Complete</Button>}{user?.role === "CUSTOMER" && booking.status === "COMPLETED" && !booking.has_review && <ReviewDialog booking={booking} />}</div></div></div>)}</div> : <Empty title="No bookings in this view" />}</>;
}
function ReviewDialog({ booking }: { booking: Booking }) { const [rating, setRating] = useState(5); const [comment, setComment] = useState(""); const client = useQueryClient(); return <Dialog><DialogTrigger asChild><Button size="sm"><Star className="size-4" />Review</Button></DialogTrigger><DialogContent><DialogTitle>Review {booking.service.name}</DialogTitle><DialogDescription>Your rating contributes to the provider's platform-wide reputation.</DialogDescription><div className="mt-5"><div className="flex gap-1">{[1,2,3,4,5].map((item) => <button key={item} onClick={() => setRating(item)} className={`text-3xl ${item <= rating ? "text-warning" : "text-border"}`}>★</button>)}</div><Textarea className="mt-4" value={comment} onChange={(e) => setComment(e.target.value)} placeholder="Share what future customers should know" /><Button className="mt-4 w-full" disabled={!comment} onClick={async () => { await ensureCsrf(); await api.post("/reviews/", formData({ booking_id: booking.id, rating, comment })); await client.invalidateQueries({ queryKey: ["bookings"] }); }}>Publish review</Button></div></DialogContent></Dialog>; }
