import { useEffect, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Bell, CheckCheck } from "lucide-react";
import { api, ensureCsrf, websocketUrl } from "@/lib/api";
import { shortDate } from "@/lib/utils";
import type { ListResponse, Notification } from "@/types/api";
import { Empty, Loading, PageIntro } from "@/components/states";
import { Button } from "@/components/ui/button";
export default function NotificationsPage() { const client = useQueryClient(); const [live, setLive] = useState<Notification[]>([]); const query = useQuery({ queryKey: ["notifications"], queryFn: async () => (await api.get<ListResponse<Notification> & { unread_count: number }>("/notifications/?page_size=50")).data }); useEffect(() => { const socket = new WebSocket(websocketUrl("/ws/notifications/")); socket.onopen = () => socket.send(JSON.stringify({ action: "get_latest" })); socket.onmessage = (event) => { const payload = JSON.parse(event.data) as { type: string; notification?: Notification; notifications?: Notification[] }; if (payload.notification) setLive((old) => [payload.notification!, ...old.filter((item) => item.id !== payload.notification!.id)]); if (payload.notifications) setLive(payload.notifications); }; return () => socket.close(); }, []); const items = live.length ? live : query.data?.results || []; const markRead = async (id: number) => { await ensureCsrf(); await api.post(`/notifications/${id}/read/`); setLive((old) => old.map((item) => item.id === id ? { ...item, read_at: new Date().toISOString() } : item)); await client.invalidateQueries({ queryKey: ["notifications"] }); }; return <><PageIntro eyebrow="Live updates" title="Notifications" description="Booking, payment, message, and review events arrive through the existing notification WebSocket." />{query.isLoading && !live.length ? <Loading /> : items.length ? <div className="space-y-3">{items.map((item) => <article key={item.id} className={`flex gap-4 rounded-2xl border bg-background p-5 shadow-card ${!item.read_at ? "border-primary/30" : ""}`}><span className={`grid size-11 shrink-0 place-items-center rounded-xl ${item.read_at ? "bg-secondary text-muted-foreground" : "bg-primary-soft text-primary"}`}><Bell className="size-5" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-bold">{item.title}</h2><p className="text-xs text-muted-foreground">{shortDate(item.created_at)}</p></div><p className="mt-1 text-sm leading-6 text-muted-foreground">{item.message}</p></div>{!item.read_at && <Button size="icon" variant="ghost" onClick={() => markRead(item.id)} title="Mark read"><CheckCheck className="size-4" /></Button>}</article>)}</div> : <Empty title="All caught up" body="New activity will appear here in real time." />}</>;
}
