import { useQuery } from "@tanstack/react-query";
import { CreditCard, RotateCcw, ShieldCheck } from "lucide-react";
import { api, ensureCsrf } from "@/lib/api";
import { money, shortDate } from "@/lib/utils";
import type { ListResponse, Payment } from "@/types/api";
import { Empty, Loading, PageIntro } from "@/components/states";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
export default function PaymentsPage() { const query = useQuery({ queryKey: ["payments"], queryFn: async () => (await api.get<ListResponse<Payment>>("/payments/?page_size=50")).data }); const retry = async (id: number) => { await ensureCsrf(); const result = await api.post<{ checkout_url: string }>(`/payments/${id}/retry/`); window.location.assign(result.data.checkout_url); }; return <><PageIntro eyebrow="Secure checkout" title="Payments" description="Stripe remains the payment processor and its signed webhook remains the source of truth for payment state." /><div className="mb-6 flex items-center gap-3 rounded-2xl border border-success/25 bg-success/5 p-4 text-sm"><ShieldCheck className="size-5 text-success" /><p><strong>Protected payments.</strong> Card details never pass through Servora or this React application.</p></div>{query.isLoading ? <Loading /> : query.data?.results.length ? <div className="overflow-hidden rounded-2xl border bg-background shadow-card"><div className="divide-y">{query.data.results.map((payment) => <div key={payment.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><span className="grid size-11 place-items-center rounded-xl bg-primary-soft text-primary"><CreditCard className="size-5" /></span><div className="min-w-0 flex-1"><p className="truncate font-bold">{payment.service_name}</p><p className="mt-1 text-xs text-muted-foreground">Booking #{payment.booking_id} · {shortDate(payment.created_at)}</p></div><Badge>{payment.payment_status}</Badge><p className="font-display text-lg font-extrabold">{money(payment.amount)}</p>{["FAILED", "PENDING"].includes(payment.payment_status) && <Button size="sm" variant="outline" onClick={() => retry(payment.id)}><RotateCcw className="size-4" />Retry</Button>}</div>)}</div></div> : <Empty title="No payment history" />}</>;
}
