import { useQuery } from "@tanstack/react-query";
import { BadgeCheck, BriefcaseBusiness, CalendarClock, MapPin, Star } from "lucide-react";
import { useParams } from "react-router-dom";
import { api } from "@/lib/api";
import type { Provider } from "@/types/api";
import { ServiceCard } from "@/components/cards";
import { Loading } from "@/components/states";
import { Badge } from "@/components/ui/badge";
export default function ProviderDetailPage() { const { id } = useParams(); const query = useQuery({ queryKey: ["provider", id], queryFn: async () => (await api.get<Provider>(`/providers/${id}/`)).data }); if (!query.data) return <Loading label="Loading provider…" />; const p = query.data; return <main className="container-page py-12"><section className="overflow-hidden rounded-3xl border bg-background shadow-card"><div className="h-32 bg-gradient-brand sm:h-44" /><div className="px-5 pb-7 sm:px-8"><div className="-mt-12 flex flex-col gap-5 sm:-mt-14 sm:flex-row sm:items-end"><div className="grid size-24 shrink-0 place-items-center overflow-hidden rounded-3xl border-4 border-background bg-gradient-brand text-3xl font-bold text-white sm:size-28">{p.profile_picture_url ? <img src={p.profile_picture_url} className="h-full w-full object-cover" alt="" /> : p.full_name.charAt(0)}</div><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h1 className="text-3xl font-extrabold">{p.full_name}</h1>{p.is_verified && <Badge><BadgeCheck className="mr-1 size-3.5" />Verified</Badge>}</div><p className="mt-2 flex items-center gap-1 text-sm text-muted-foreground"><MapPin className="size-4" />{p.address || p.city || "Local provider"}</p></div></div><p className="mt-6 max-w-3xl leading-7 text-muted-foreground">{p.description || "Experienced local professional ready to help with your next project."}</p><div className="mt-7 grid gap-3 sm:grid-cols-3"><Stat icon={Star} value={p.average_rating.toFixed(1)} label={`${p.review_count} provider-wide reviews`} /><Stat icon={BriefcaseBusiness} value={String(p.jobs_completed)} label="Jobs completed" /><Stat icon={CalendarClock} value={`${p.experience_years} years`} label="Experience" /></div></div></section><section className="mt-12"><h2 className="text-2xl font-extrabold">Services by {p.full_name}</h2><div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{p.services?.map((service) => <ServiceCard key={service.id} service={service} />)}</div></section>{p.latest_reviews?.length ? <section className="mt-12"><h2 className="text-2xl font-extrabold">Recent reviews</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{p.latest_reviews.map((review) => <article key={review.id} className="rounded-2xl border bg-background p-5 shadow-card"><div className="flex justify-between"><p className="font-bold">{review.customer.full_name}</p><span className="text-warning">{"★".repeat(review.rating)}</span></div><p className="mt-3 text-sm leading-6 text-muted-foreground">{review.comment}</p></article>)}</div></section> : null}</main>; }
function Stat({ icon: Icon, value, label }: { icon: typeof Star; value: string; label: string }) { return <div className="flex items-center gap-3 rounded-2xl bg-secondary p-4"><span className="grid size-10 place-items-center rounded-xl bg-background text-primary"><Icon className="size-5" /></span><div><p className="font-display text-lg font-extrabold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div></div>; }
