# Generated by Django 6.0.6 on 2026-06-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_legacy_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=23.0225, max_digits=9),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=72.5714, max_digits=9),
        ),
    ]
